### ISSUE TITLE
Angular.js README crashes the application

### ISSUE THREAD

**Issue by eladmoshe** [rlofc/understate#2]
output: 
Traceback (most recent call last):
  File "./understate", line 22, in <module>
    Parser(CursesRenderer()).parse(f.read())
  File "/home/elad/work/understate/uslib/parser.py", line 46, in parse
    output = r[Parser.M_RENDERER](groups)
  File "/home/elad/work/understate/uslib/render.py", line 98, in onCode
    highlight(text,get_lexer_by_name(syntax),UnderstateFormatter(style='monokai'),subwin)
  File "/home/elad/work/understate/uslib/pygmentsext.py", line 39, in **init**
    self._setup_styles() # convert selected style's colors to term. colors
  File "/home/elad/work/understate/uslib/pygmentsext.py", line 18, in _setup_styles
    curses.init_pair(index,fg,bg)
_curses.error: init_pair() returned ERR

**Comment by ithailevi** [comment]
Seems like curses is failing to create the pygments color table. This may be specific to your runtime environment / terminal - possibly due to 256 color support in the terminal (or lack of). What terminal and OS are you running?

**Comment by eladmoshe** [comment]
Ubuntu 64 bit with zsh

**Comment by eladmoshe** [comment]
By the way, other files worked fine (e.g. Bootstrap), so it must be something specific to this file.
